export type BaseBB = {
  id?: number | string;
};

export type BBPermission =
  | "ZFGC_USER"
  | "ZFGC_GUEST"
  | "ZFGC_PROFILE_VIEWER"
  | "ZFGC_PROFILE_EDITOR"
  | "ZFGC_PROFILE_ADMIN"
  | "ZFGC_MESSAGE_VIEWER"
  | "ZFGC_MESSAGE_EDITOR"
  | "ZFGC_MESSAGE_ADMIN"
  | "ZFGC_READ_ONLY"
  | "ZFGC_SITE_ADMIN"
  | "ZFGC_SITE_MODERATOR"
  | "ZFGC_WIKI_MODERATOR";
