import type { Plugin, ViteDevServer } from "vite";
import { promises as fs } from "node:fs";
import path from "node:path";

interface ImagePathPluginOptions {
  assetsPath?: string;
  includeAssetDirs?: string[];
  outputTypeDir?: string;
  outputClientDir?: string;
  outputServerDir?: string;
  debug?: boolean;
}

function defaultOptions(): Required<ImagePathPluginOptions> {
  return {
    assetsPath: "public",
    includeAssetDirs: ["images", "themes"],
    outputTypeDir: "build/types",
    outputClientDir: "build/client/assets",
    outputServerDir: "build/server/assets",
    debug: false,
  };
}

async function walk(dir: string): Promise<string[]> {
  const entries = await fs
    .readdir(dir, { withFileTypes: true })
    .catch(() => []);
  const files = await Promise.all(
    entries.map(async (entry) => {
      const fullPath = path.join(dir, entry.name);
      return entry.isDirectory() ? await walk(fullPath) : fullPath;
    }),
  );
  return files.flat();
}

function toPascalCase(input: string) {
  return (
    input.replace(/(^\w|-\w|_\w)/g, (fragment) =>
      fragment.replace(/[-_]/, "").toUpperCase(),
    ) + "Path"
  );
}

/**
 * Writes the TypeScript definitions from the cached Map.
 */
async function writeTypeFile(
  options: Required<ImagePathPluginOptions>,
  fileCache: Map<string, Set<string>>,
) {
  const outputPath = path.resolve(
    process.cwd(),
    `${options.outputTypeDir}/image-paths.d.ts`,
  );

  if (options.debug)
    console.debug(
      `[vite-plugin-generate-image-paths] Generating ${outputPath}`,
    );

  await fs.mkdir(path.dirname(outputPath), { recursive: true });

  const typeBlocks: string[] = [];
  for (const [subDir, files] of fileCache) {
    const typeName = toPascalCase(subDir);
    const literals =
      [...files].map((filePath) => `"${filePath}"`).join(" |\n    ") || "never";
    typeBlocks.push(`  export type ${typeName} =\n    ${literals};`);
  }

  const contents = `/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
// --- GENERATED BY vite-plugin-generate-image-paths ---
declare global {
${typeBlocks.join("\n\n")}
}

export {};
// --- END GENERATED BY vite-plugin-generate-image-paths ---
`.trim();

  await fs.writeFile(outputPath, contents + "\n", "utf-8");
  if (options.debug)
    console.debug(`[vite-plugin-generate-image-paths] Wrote ${outputPath}`);
}

/**
 * Initializes a Map-based cache from disk.
 */
async function initFileCache(options: Required<ImagePathPluginOptions>) {
  const cache = new Map<string, Set<string>>();
  const assetsAbsPath = path.resolve(process.cwd(), options.assetsPath);

  if (options.debug)
    console.debug(
      `[vite-plugin-generate-image-paths] Initializing cache from ${assetsAbsPath}`,
    );

  await Promise.all(
    options.includeAssetDirs.map(async (subDir) => {
      const fullDir = path.join(assetsAbsPath, subDir);
      const files = await walk(fullDir);
      const relativeFiles = files.map((filePath) =>
        path.relative(assetsAbsPath, filePath).replace(/\\/g, "/"),
      );
      cache.set(subDir, new Set(relativeFiles));
    }),
  );

  if (options.debug)
    console.debug(
      `[vite-plugin-generate-image-paths] Initialized cache with ${cache.size} entries`,
    );

  return cache;
}

/**
 * Vite plugin that generates TypeScript type definitions for asset paths in your project.
 *
 * This plugin scans specified directories within your assets folder and generates
 * type-safe path definitions (e.g., `ImagePath`, `ThemePath`) that can be used with
 * the {@link BBImage} component. Types are automatically regenerated during development
 * when files are added or removed.
 *
 * @param userOptions - Configuration options for the plugin @see {@link ImagePathPluginOptions}
 * @param userOptions.assetsPath - Root directory for assets (default: "public")
 * @param userOptions.includeAssetDirs - Array of subdirectories to scan for generating types (default: ["images", "themes"])
 * @param userOptions.outputTypeDir - Tyoe output directory (default: "build")
 * @param userOptions.outputClientDir - Client assets output directory (default: "build/client/assets")
 * @param userOptions.outputServerDir - Server assets output directory (default: "build/server/assets")
 * @param userOptions.debug - Enable debug logging (default: false)
 *
 * @returns An array of Vite plugins
 *
 * @example
 * ```ts
 * // vite.config.ts
 * import { defineConfig } from "vite";
 * import { generateImagePaths } from "./vite/plugins/vite-plugin-generate-image-paths";
 *
 * export default defineConfig({
 *   plugins: [
 *     generateImagePaths(),
 *   ],
 * });
 * ```
 *
 * @example
 * Generated type file structure:
 * ```ts
 * declare global {
 *   export type ImagesPath = "images/logo.png" | "images/hero.jpg";
 *   export type ThemesPath = "themes/midnight/board-summary/off.gif" | "themes/midnight/post/xx.gif";
 * }
 * ```
 *
 * @see {@link BBImage}
 */
export function generateImagePaths(
  userOptions: ImagePathPluginOptions = {},
): Plugin[] {
  const options = { ...defaultOptions(), ...userOptions };
  const assetsAbsPath = path.resolve(process.cwd(), options.assetsPath);

  let fileCache: Map<string, Set<string>> = new Map();
  let debounceTimer: NodeJS.Timeout | null = null;

  const triggerRegeneration = async () => {
    if (debounceTimer) clearTimeout(debounceTimer);
    debounceTimer = setTimeout(async () => {
      await writeTypeFile(options, fileCache);
    }, 100);
  };

  const updateCache = (filePath: string, added: boolean) => {
    const relPath = path.relative(assetsAbsPath, filePath); //.replace(/\\/g, "/");
    const subDir = options.includeAssetDirs.find((d) =>
      relPath.startsWith(`${d}/`),
    );
    if (!subDir) return;

    const dirSet = fileCache.get(subDir) ?? new Set<string>();
    if (added) dirSet.add(relPath);
    else dirSet.delete(relPath);
    fileCache.set(subDir, dirSet);
  };

  return [
    {
      name: "vite-plugin-generate-image-paths",
      apply: "serve",
      async buildStart() {
        fileCache.clear();
        fileCache = await initFileCache(options);
        await writeTypeFile(options, fileCache);
      },
      async configureServer(server: ViteDevServer) {
        fileCache.clear();
        fileCache = await initFileCache(options);
        await writeTypeFile(options, fileCache);

        const watchDirs = options.includeAssetDirs.map((dir) =>
          path.resolve(assetsAbsPath, dir),
        );
        if (options.debug)
          console.debug(
            `[vite-plugin-generate-image-paths] Watching ${watchDirs.join(
              ", ",
            )}`,
          );

        server.watcher.add(watchDirs);
        server.watcher.on("add", (file) => {
          updateCache(file, true);
          void triggerRegeneration();
        });

        server.watcher.on("unlink", (file) => {
          updateCache(file, false);
          void triggerRegeneration();
        });
      },
      async closeBundle() {
        fileCache.clear();
        fileCache = await initFileCache(options);
        await writeTypeFile(options, fileCache);
      },
    },
  ];
}
