name: CI

on:
  pull_request:
    paths:
      - "package.json"
      - "yarn.lock"
      - ".nvmrc"
      - ".github/**/*"
      - "src/**/*"

permissions:
  contents: read

concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ZeldaFanGameCentral/github-common/actions/setup-node-yarn@main
      - run: rm -rf build
      - run: yarn build
      - run: yarn check

  dependabot:
    runs-on: ubuntu-latest
    needs: build
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: ZeldaFanGameCentral/github-common/actions/auto-approve-dependabot@main
