name: Auto Merge Dependabot Security Updates
on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    
permissions:
  contents: read
  pull-requests: write
  
jobs:
  call-automerge:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/auto-merge-dependabot-reusable.yml
