on:
  workflow_call:
    inputs:
      environment:
        required: false
        type: string
        default: ${{ github.ref_name }}
        description: "The environment to build for (e.g., main, development). Defaults to the branch name."
      deployment_target:
        required: false
        default: production
        type: string
        description: "The deployment target to use (e.g., production,github-pages, netlify, vercel, etc.)"
    outputs:
      artifact_name:
        description: "The name of the build artifact"
        value: ${{ jobs.build.outputs.artifact_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: 1
      GITHUB_PAGES: ${{ inputs.deployment_target == 'github-pages' }}
      VITE_MODE: ${{ inputs.deployment_target || 'production' }}

    outputs:
      artifact_name: ${{ inputs.environment }}-build
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          # cache: yarn FIXME: uncomment when https://github.com/actions/setup-node/issues/531 is closed.
      - run: npm install -g corepack@latest && corepack enable

      - name: Use Node.js (yarn cache workaround) # FIXME: uncomment when https://github.com/actions/setup-node/issues/531 is closed.
        id: yarn-cache
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: yarn

      - if: ${{ steps.yarn-cache.outputs.cache-hit != 'true' }}
        run: yarn install --immutable

      - if: ${{ steps.yarn-cache.outputs.cache-hit == 'true' }}
        run: yarn install --immutable --immutable-cache

      - run: yarn build --mode="${{ inputs.deployment_target }}"
      - run: yarn check

      - if: ${{ inputs.deployment_target == 'github-pages' }}
        name: Copy 404 page to workaround gh pages routing
        run: cp ./.github/404.html ./build/client/404.html #see https://github.com/orgs/community/discussions/64096

      - name: Upload build artifact
        if: ${{ inputs.deployment_target == 'github-pages' }}
        uses: actions/upload-pages-artifact@v3
        with:
          name: ${{ inputs.environment }}-build
          path: build/client
          retention-days: 1
