name: CI
on:
  pull_request:

permissions:
  contents: read

env:
  CI: 1

concurrency:
  group: "ci-${{ github.head_ref }}"
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      environment: ${{ github.head_ref }}
