name: CI
# trigger on changes to package.json, yarn.lock, .nvmrc, or .github/workflows/*.yml or src/**/* files
on:
  push:
    paths:
      - "package.json"
      - "yarn.lock"
      - ".nvmrc"
      - ".github/workflows/*.yml"
      - "src/**/*"

permissions:
  contents: read

env:
  CI: 1

concurrency:
  group: "ci-${{ github.head_ref }}"
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      environment: ${{ github.head_ref }}
